version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - jketelaar
  assignees:
  - jketelaar
  ignore:
  - dependency-name: github.com/hashicorp/boundary/sdk
    versions:
    - 0.0.4
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.3
