package cmd

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/intercube/cli/util/appconfig"
	authutil "github.com/intercube/cli/util/auth"
	setupapi "github.com/intercube/cli/util/setup"
	"github.com/manifoldco/promptui"
	"github.com/spf13/cobra"
)

var (
	setupEnvironment  string
	setupBranch       string
	setupDomain       string
	setupDirectory    string
	setupPlan         string
	setupOrganization string
	setupServerID     int
	setupNoCharge     bool
	setupExistingSite bool
	setupYes          bool
)

var domainPattern = regexp.MustCompile(`(?i)^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z](?:[a-z0-9-]{0,61}[a-z0-9])$`)

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Set up this GitHub repository on Intercube",
	Args:  cobra.NoArgs,
	RunE:  runSetup,
}

func init() {
	setupCmd.Flags().StringVarP(&setupEnvironment, "environment", "e", "", "environment name")
	setupCmd.Flags().StringVarP(&setupBranch, "branch", "b", "", "Git branch to deploy")
	setupCmd.Flags().StringVar(&setupDomain, "domain", "", "custom domain (managed mycube.dev names are generated by Intercube)")
	setupCmd.Flags().StringVarP(&setupDirectory, "directory", "d", "", "application directory inside the repository")
	setupCmd.Flags().StringVarP(&setupPlan, "plan", "p", "", "server plan key override")
	setupCmd.Flags().StringVarP(&setupOrganization, "organization", "o", "", "organization id override")
	setupCmd.Flags().IntVar(&setupServerID, "server", 0, "existing server id (platform admins only)")
	setupCmd.Flags().BoolVar(&setupNoCharge, "no-charge", false, "create without billing (platform admins only)")
	setupCmd.Flags().BoolVarP(&setupExistingSite, "existing-site", "s", false, "connect this repository to an existing site")
	setupCmd.Flags().BoolVarP(&setupYes, "yes", "y", false, "accept suggested values and confirm creation")
	rootCmd.AddCommand(setupCmd)
}

func runSetup(cmd *cobra.Command, _ []string) error {
	if setupExistingSite {
		for _, flag := range []string{"domain", "plan", "server", "no-charge"} {
			if cmd.Flags().Changed(flag) {
				return fmt.Errorf("--%s cannot be used with --existing-site", flag)
			}
		}
	}
	if setupServerID > 0 && !setupNoCharge {
		return errors.New("--server requires --no-charge; organization users cannot add sites to existing servers")
	}

	repositoryRoot, err := gitOutput(cmd.Context(), "rev-parse", "--show-toplevel")
	if err != nil {
		return errors.New("run `intercube setup` inside a Git repository")
	}
	remote, err := gitOutputAt(cmd.Context(), repositoryRoot, "remote", "get-url", "origin")
	if err != nil {
		return errors.New("this repository needs a GitHub `origin` remote before it can be set up")
	}
	owner, repository, err := parseGitHubRemote(remote)
	if err != nil {
		return err
	}

	client, organizationID, err := newSetupClient(cmd, setupOrganization)
	if err != nil {
		return err
	}
	configPath := filepath.Join(repositoryRoot, ".intercube.yaml")
	projectConfig, err := setupapi.LoadProjectConfig(configPath)
	if err != nil {
		return err
	}
	if setupExistingSite {
		return runExistingSiteSetup(cmd, client, organizationID, repositoryRoot, owner, repository, configPath, projectConfig)
	}

	if handled, err := handleExistingSetups(cmd, client, configPath, projectConfig); handled || err != nil {
		return err
	}

	branch, analysis, err := analyzeSetupRepository(cmd, client, repositoryRoot, owner, repository)
	if err != nil {
		return err
	}

	environment := strings.TrimSpace(setupEnvironment)
	if environment == "" {
		environment = defaultEnvironment(branch)
		if _, exists := projectConfig.Environments[environment]; exists {
			environment = branchEnvironment(branch)
		}
		if !setupYes && !runtimeContext.NonInteractive {
			environment, err = promptValue("Environment", environment, validateEnvironment)
			if err != nil {
				return err
			}
		}
	}
	if _, exists := projectConfig.Environments[environment]; exists {
		return fmt.Errorf("environment %q is already configured", environment)
	}

	domain := strings.TrimSpace(setupDomain)
	if domain == "" {
		domain = analysis.SuggestedDomain
		if !setupYes && !runtimeContext.NonInteractive {
			domain, err = promptValue("Domain", analysis.SuggestedDomain, func(value string) error {
				return validateSetupDomain(value, analysis.SuggestedDomain)
			})
			if err != nil {
				return err
			}
		}
	}
	if err := validateSetupDomain(domain, analysis.SuggestedDomain); err != nil {
		return err
	}

	domains := []string{domain}
	if !strings.EqualFold(domain, analysis.SuggestedDomain) {
		domains = append(domains, analysis.SuggestedDomain)
	}
	installations := make([]setupapi.InstallationRequest, 0, len(analysis.Installations))
	for _, installation := range analysis.Installations {
		installations = append(installations, setupapi.InstallationRequest{Type: installation})
	}
	var runtimeSelection *setupapi.RuntimeRequest
	if analysis.Runtime != "" {
		runtimeSelection = &setupapi.RuntimeRequest{Type: analysis.Runtime, Version: analysis.RuntimeVersion}
	}
	resourceKind := "server"
	if setupServerID > 0 {
		resourceKind = "site"
	}
	payload := setupapi.ProvisioningPayload{
		ResourceKind:     resourceKind,
		ServerID:         setupServerID,
		Environment:      environment,
		Domains:          domains,
		Framework:        analysis.Framework,
		Runtime:          analysis.Runtime,
		DomainName:       domain,
		MainDomainName:   domain,
		ServerPlanKey:    setupPlan,
		RuntimeSelection: runtimeSelection,
		Installations:    installations,
		Repository: setupapi.RepositoryRequest{
			URL:                  fmt.Sprintf("https://github.com/%s/%s.git", owner, repository),
			Branch:               branch,
			Directory:            setupDirectory,
			WorkflowKey:          analysis.WorkflowKey,
			ContinuousDeployment: true,
		},
	}
	idempotencyKey := setupIdempotencyKey(owner, repository, environment, branch)
	quoteResponse, err := client.Quote(cmd.Context(), setupapi.QuoteRequest{
		OrganizationID: organizationID,
		IdempotencyKey: idempotencyKey,
		BillingPeriod:  "MONTH",
		NoCharge:       setupNoCharge,
		Payload:        payload,
	})
	if err != nil {
		return err
	}

	projectConfig.Version = 1
	projectConfig.Repository = setupapi.ProjectRepository{URL: payload.Repository.URL, Directory: setupDirectory}
	projectConfig.Environments[environment] = setupapi.Environment{
		Branch:         branch,
		Domain:         domain,
		ManagedDomain:  analysis.SuggestedDomain,
		IntentID:       quoteResponse.Intent.ID,
		IntentRevision: quoteResponse.Intent.Revision,
		QuoteID:        quoteResponse.Quote.QuoteID,
		IdempotencyKey: idempotencyKey,
		NoCharge:       setupNoCharge,
		Status:         "validated",
		Prepared:       preparedSetupSnapshot(analysis, quoteResponse, setupDirectory, setupServerID),
	}
	if err := setupapi.SaveProjectConfig(configPath, projectConfig); err != nil {
		return err
	}

	printSetupSummary(environment, branch, domain, analysis, quoteResponse, setupNoCharge, setupServerID)
	if !setupYes {
		if runtimeContext.NonInteractive {
			return errors.New("non-interactive setup requires --yes after reviewing the prepared .intercube.yaml")
		}
		confirmed, err := promptConfirm("Create this setup?", false)
		if err != nil {
			return err
		}
		if !confirmed {
			fmt.Printf("Setup prepared in %s. Run `intercube setup` to continue.\n", configPath)
			return nil
		}
	}

	progress, err := client.Create(cmd.Context(), setupapi.CreateRequest{
		OrganizationID: organizationID,
		IdempotencyKey: "create-" + idempotencyKey,
		IntentID:       quoteResponse.Intent.ID,
		IntentRevision: quoteResponse.Intent.Revision,
		QuoteID:        quoteResponse.Quote.QuoteID,
		BillingPeriod:  "MONTH",
		NoCharge:       setupNoCharge,
	})
	if err != nil {
		return err
	}
	return followSetup(cmd, client, configPath, projectConfig, environment, progress)
}

func analyzeSetupRepository(
	cmd *cobra.Command,
	client *setupapi.Client,
	repositoryRoot, owner, repository string,
) (string, *setupapi.RepositoryAnalysis, error) {
	currentBranch, _ := gitOutputAt(cmd.Context(), repositoryRoot, "branch", "--show-current")
	analysis, err := analyzeUntilLinked(cmd, client, setupapi.RepositoryAnalysisRequest{
		Owner: owner, Repository: repository, Branch: strings.TrimSpace(setupBranch), Directory: setupDirectory,
	})
	if err != nil {
		return "", nil, setupAnalysisError(err)
	}

	branch := strings.TrimSpace(setupBranch)
	if branch == "" {
		branch = analysis.DefaultBranch
		if currentBranch != "" && currentBranch != analysis.DefaultBranch && !setupYes && !runtimeContext.NonInteractive {
			selection := promptui.Select{
				Label:     fmt.Sprintf("GitHub defaults to %s, but you have %s checked out", analysis.DefaultBranch, currentBranch),
				Items:     []string{analysis.DefaultBranch, currentBranch},
				Templates: simpleSelectTemplates("branch"),
			}
			_, branch, err = selection.Run()
			if err != nil {
				return "", nil, err
			}
		}
	}
	if branch == "" {
		return "", nil, errors.New("GitHub did not return a default branch; pass --branch")
	}

	if branch != analysis.Branch {
		analysis, err = analyzeUntilLinked(cmd, client, setupapi.RepositoryAnalysisRequest{
			Owner: owner, Repository: repository, Branch: branch, Directory: setupDirectory,
		})
		if err != nil {
			return "", nil, setupAnalysisError(err)
		}
	}
	return branch, analysis, nil
}

func setupAnalysisError(err error) error {
	if setupDirectory == "" && strings.Contains(strings.ToLower(err.Error()), "no supported") {
		return fmt.Errorf("%w; if the application is not at the repository root, pass --directory or -d", err)
	}
	return err
}

func newSetupClient(cmd *cobra.Command, organizationOverride string) (*setupapi.Client, string, error) {
	appconfig.LoadFromEnv()
	if err := appconfig.ValidateClerk(); err != nil {
		return nil, "", err
	}
	if err := appconfig.ValidateInventory(); err != nil {
		return nil, "", err
	}
	store, err := authutil.NewSessionStore("intercube-cli")
	if err != nil {
		return nil, "", err
	}
	organizationID, _, err := resolveOrganizationID(cmd, organizationOverride)
	if err != nil {
		return nil, "", err
	}
	if organizationID == "" {
		return nil, "", errors.New("no organization selected; run `intercube auth org select`")
	}
	clerk := &authutil.ClerkClient{
		Issuer: appconfig.ClerkIssuer, ClientID: appconfig.ClerkClientID, Audience: appconfig.ClerkAudience,
		Scopes: appconfig.ClerkScopes, CallbackPort: appconfig.ParsedCallbackPort(),
	}
	client := setupapi.NewClient(appconfig.InventoryAPIBaseURL, organizationID, store, clerk)
	githubToken, tokenErr := setupapi.LoadGitHubToken()
	if tokenErr != nil {
		return nil, "", fmt.Errorf("unable to load GitHub authorization: %w", tokenErr)
	}
	client.GitHubToken = githubToken
	return client, organizationID, nil
}

func analyzeUntilLinked(cmd *cobra.Command, client *setupapi.Client, request setupapi.RepositoryAnalysisRequest) (*setupapi.RepositoryAnalysis, error) {
	analysis, err := client.AnalyzeRepository(cmd.Context(), request)
	if err != nil {
		return nil, err
	}
	if analysis.GitHubLinked {
		return analysis, nil
	}
	if analysis.GitHubAuthorizationRequired && analysis.GitHubClientID != "" {
		if runtimeContext.NonInteractive {
			return nil, errors.New("GitHub authorization is required; rerun interactively to connect the Intercube GitHub App")
		}
		authorization, err := setupapi.StartGitHubDeviceAuthorization(cmd.Context(), analysis.GitHubClientID)
		if err != nil {
			return nil, err
		}
		fmt.Printf("Authorize Intercube on GitHub with code %s\n", authorization.UserCode)
		fmt.Printf("Opening %s\n", authorization.VerificationURI)
		if err := authutil.OpenBrowser(authorization.VerificationURI); err != nil {
			fmt.Printf("Open the link manually: %s\n", authorization.VerificationURI)
		}
		token, err := setupapi.PollGitHubDeviceAuthorization(cmd.Context(), analysis.GitHubClientID, authorization)
		if err != nil {
			return nil, err
		}
		if err := setupapi.SaveGitHubToken(token); err != nil {
			return nil, fmt.Errorf("unable to store GitHub authorization securely: %w", err)
		}
		client.GitHubToken = token
		analysis, err = client.AnalyzeRepository(cmd.Context(), request)
		if err != nil {
			return nil, err
		}
		if analysis.GitHubLinked {
			fmt.Println("GitHub repository linked.")
			return analysis, nil
		}
	}
	if runtimeContext.NonInteractive {
		return nil, fmt.Errorf("GitHub repository is not linked; install the Intercube GitHub App: %s", analysis.GitHubInstallURL)
	}

	fmt.Printf("Intercube needs access to %s/%s.\n", request.Owner, request.Repository)
	fmt.Printf("Opening %s\n", analysis.GitHubInstallURL)
	if err := authutil.OpenBrowser(analysis.GitHubInstallURL); err != nil {
		fmt.Printf("Open the link manually: %s\n", analysis.GitHubInstallURL)
	}
	fmt.Println("Waiting for GitHub linking to finish...")
	ticker := time.NewTicker(3 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-cmd.Context().Done():
			return nil, cmd.Context().Err()
		case <-ticker.C:
			analysis, err = client.AnalyzeRepository(cmd.Context(), request)
			if err != nil {
				return nil, err
			}
			if analysis.GitHubLinked {
				fmt.Println("GitHub repository linked.")
				return analysis, nil
			}
		}
	}
}

func handleExistingSetups(
	cmd *cobra.Command,
	client *setupapi.Client,
	configPath string,
	config *setupapi.ProjectConfig,
) (bool, error) {
	names := setupapi.EnvironmentNames(config)
	if len(names) == 0 {
		return false, nil
	}

	for _, name := range names {
		environment := config.Environments[name]
		if environment.IntentID == "" || (setupEnvironment != "" && setupEnvironment != name) {
			continue
		}
		progress, err := client.Progress(cmd.Context(), environment.IntentID)
		if err != nil {
			return true, err
		}
		if progress.SetupStatus == "ready" {
			updateEnvironmentProgress(config, name, progress)
			_ = setupapi.SaveProjectConfig(configPath, config)
			if setupEnvironment == name {
				fmt.Printf("Environment %s is already configured and ready.\n", name)
				return true, nil
			}
			continue
		}

		if setupEnvironment == name || setupYes || (!runtimeContext.NonInteractive && mustConfirm("Resume the interrupted "+name+" setup?", true)) {
			if preparedSetupOptionsChanged(cmd, config, environment) {
				applyPreparedSetupDefaults(cmd, config, name, environment)
				delete(config.Environments, name)
				fmt.Println("Setup options changed; preparing a new configuration and quote.")
				return false, nil
			}
			if progress.SetupStatus == "validated" {
				if environment.IntentRevision == "" || environment.IdempotencyKey == "" {
					return true, errors.New("prepared setup is missing resume metadata; remove that environment from .intercube.yaml and run setup again")
				}
				printPreparedSetupSummary(name, config, environment)
				if !setupYes {
					if runtimeContext.NonInteractive {
						return true, errors.New("non-interactive setup requires --yes to confirm the prepared setup")
					}
					confirmed, confirmErr := promptConfirm("Create this prepared setup?", false)
					if confirmErr != nil || !confirmed {
						return true, confirmErr
					}
				}
				progress, err = client.Create(cmd.Context(), setupapi.CreateRequest{
					OrganizationID: client.OrgID,
					IdempotencyKey: "create-" + environment.IdempotencyKey,
					IntentID:       environment.IntentID,
					IntentRevision: environment.IntentRevision,
					QuoteID:        environment.QuoteID,
					BillingPeriod:  "MONTH",
					NoCharge:       environment.NoCharge,
				})
				if err != nil {
					return true, err
				}
			}
			if progress.SetupStatus == "failed" {
				if runtimeContext.NonInteractive {
					return true, errors.New("setup failed; rerun interactively to explicitly retry it")
				}
				retry, err := promptConfirm("Retry this failed setup?", false)
				if err != nil {
					return true, err
				}
				if !retry {
					return true, errors.New("setup failed")
				}
				progress, err = client.Retry(cmd.Context(), environment.IntentID)
				if err != nil {
					return true, err
				}
			}
			return true, followSetup(cmd, client, configPath, config, name, progress)
		}
	}

	fmt.Printf("This repository already has %s configured.\n", strings.Join(names, ", "))
	if setupEnvironment != "" || setupYes {
		return false, nil
	}
	if runtimeContext.NonInteractive {
		return true, errors.New("pass --environment to set up another environment")
	}
	more, err := promptConfirm("Set up another environment?", true)
	return !more, err
}

func followSetup(
	cmd *cobra.Command,
	client *setupapi.Client,
	configPath string,
	config *setupapi.ProjectConfig,
	environment string,
	progress *setupapi.Progress,
) error {
	lastStage := ""
	for {
		if progress.SetupStage != lastStage {
			fmt.Printf("[%s] %s\n", progress.SetupStage, progress.SetupMessage)
			lastStage = progress.SetupStage
		}
		updateEnvironmentProgress(config, environment, progress)
		if err := setupapi.SaveProjectConfig(configPath, config); err != nil {
			return err
		}
		switch progress.SetupStatus {
		case "ready":
			fmt.Printf("Setup complete. Server %d and site %d are now tracked in Intercube.\n", progress.ServerID, progress.SiteID)
			return nil
		case "failed":
			fmt.Println("Setup failed. Intercube will not retry it automatically.")
			if progress.FailureMessage != "" && Verbose {
				fmt.Println(progress.FailureMessage)
			}
			if runtimeContext.NonInteractive {
				return errors.New("setup failed")
			}
			retry, err := promptConfirm("Retry this setup?", false)
			if err != nil {
				return err
			}
			if !retry {
				return errors.New("setup failed")
			}
			progress, err = client.Retry(cmd.Context(), progress.ID)
			if err != nil {
				return err
			}
		default:
			select {
			case <-cmd.Context().Done():
				return cmd.Context().Err()
			case <-time.After(5 * time.Second):
			}
			var err error
			progress, err = client.Progress(cmd.Context(), progress.ID)
			if err != nil {
				return err
			}
		}
	}
}

func updateEnvironmentProgress(config *setupapi.ProjectConfig, name string, progress *setupapi.Progress) {
	environment := config.Environments[name]
	environment.Status = progress.SetupStatus
	if progress.ServerID > 0 {
		environment.ServerID = progress.ServerID
	}
	if progress.SiteID > 0 {
		environment.SiteID = progress.SiteID
	}
	config.Environments[name] = environment
}

func printSetupSummary(
	environment, branch, domain string,
	analysis *setupapi.RepositoryAnalysis,
	quote *setupapi.QuoteResponse,
	noCharge bool,
	serverID int,
) {
	fmt.Println("\nSetup summary")
	fmt.Printf("  Repository:  %s\n", analysis.Repository)
	fmt.Printf("  Branch:      %s\n", branch)
	fmt.Printf("  Environment: %s\n", environment)
	fmt.Printf("  Application: %s", analysis.Framework)
	if analysis.Runtime != "" {
		fmt.Printf(" (%s %s)", analysis.Runtime, analysis.RuntimeVersion)
	}
	fmt.Println()
	fmt.Printf("  Domain:      %s\n", domain)
	if !strings.EqualFold(domain, analysis.SuggestedDomain) {
		fmt.Printf("  Managed URL: %s\n", analysis.SuggestedDomain)
	}
	if serverID > 0 {
		fmt.Printf("  Server:      existing server %d\n", serverID)
	} else if profile := quote.Intent.Classification.ServerProfile; profile != nil {
		label := profile.Label
		if label == "" {
			label = profile.Key
		}
		fmt.Printf("  Plan:        %s (%d vCPU, %d GB RAM)\n", label, profile.Cores, profile.MemoryGB)
	}
	if noCharge {
		fmt.Println("  Price:       no charge (platform admin)")
	} else {
		fmt.Printf("  Price:       %.2f %s/month\n", quote.Quote.Amount, quote.Quote.Currency)
	}
	fmt.Println()
}

func preparedSetupSnapshot(
	analysis *setupapi.RepositoryAnalysis,
	quote *setupapi.QuoteResponse,
	directory string,
	serverID int,
) *setupapi.PreparedSetup {
	prepared := &setupapi.PreparedSetup{
		Repository:     analysis.Repository,
		Directory:      directory,
		Framework:      analysis.Framework,
		Runtime:        analysis.Runtime,
		RuntimeVersion: analysis.RuntimeVersion,
		ServerID:       serverID,
		PriceAmount:    quote.Quote.Amount,
		PriceCurrency:  quote.Quote.Currency,
	}
	if profile := quote.Intent.Classification.ServerProfile; profile != nil {
		prepared.PlanKey = profile.Key
		prepared.PlanLabel = profile.Label
		prepared.PlanCores = profile.Cores
		prepared.PlanMemoryGB = profile.MemoryGB
	}
	return prepared
}

func printPreparedSetupSummary(name string, config *setupapi.ProjectConfig, environment setupapi.Environment) {
	prepared := environment.Prepared
	if prepared == nil {
		prepared = &setupapi.PreparedSetup{Repository: config.Repository.URL, Directory: config.Repository.Directory}
	}

	fmt.Println("\nPrepared setup summary")
	fmt.Printf("  Repository:  %s\n", prepared.Repository)
	fmt.Printf("  Branch:      %s\n", environment.Branch)
	if prepared.Directory != "" {
		fmt.Printf("  Directory:   %s\n", prepared.Directory)
	}
	fmt.Printf("  Environment: %s\n", name)
	if prepared.Framework != "" {
		fmt.Printf("  Application: %s", prepared.Framework)
		if prepared.Runtime != "" {
			fmt.Printf(" (%s %s)", prepared.Runtime, prepared.RuntimeVersion)
		}
		fmt.Println()
	}
	fmt.Printf("  Domain:      %s\n", environment.Domain)
	if !strings.EqualFold(environment.Domain, environment.ManagedDomain) {
		fmt.Printf("  Managed URL: %s\n", environment.ManagedDomain)
	}
	if prepared.ServerID > 0 {
		fmt.Printf("  Server:      existing server %d\n", prepared.ServerID)
	} else if prepared.PlanKey != "" {
		label := prepared.PlanLabel
		if label == "" {
			label = prepared.PlanKey
		}
		fmt.Printf("  Plan:        %s (%d vCPU, %d GB RAM)\n", label, prepared.PlanCores, prepared.PlanMemoryGB)
	}
	if environment.NoCharge {
		fmt.Println("  Price:       no charge (platform admin)")
	} else if prepared.PriceCurrency != "" {
		fmt.Printf("  Price:       %.2f %s/month\n", prepared.PriceAmount, prepared.PriceCurrency)
	} else {
		fmt.Println("  Price:       unavailable; change a setup option to prepare a new quote")
	}
	fmt.Println()
}

func preparedSetupOptionsChanged(cmd *cobra.Command, config *setupapi.ProjectConfig, environment setupapi.Environment) bool {
	prepared := environment.Prepared
	if cmd.Flags().Changed("branch") && strings.TrimSpace(setupBranch) != environment.Branch {
		return true
	}
	if cmd.Flags().Changed("domain") && strings.TrimSpace(setupDomain) != environment.Domain {
		return true
	}
	if cmd.Flags().Changed("directory") && strings.TrimSpace(setupDirectory) != config.Repository.Directory {
		return true
	}
	if cmd.Flags().Changed("plan") && (prepared == nil || strings.TrimSpace(setupPlan) != prepared.PlanKey) {
		return true
	}
	if cmd.Flags().Changed("server") && (prepared == nil || setupServerID != prepared.ServerID) {
		return true
	}
	return cmd.Flags().Changed("no-charge") && setupNoCharge != environment.NoCharge
}

func applyPreparedSetupDefaults(cmd *cobra.Command, config *setupapi.ProjectConfig, name string, environment setupapi.Environment) {
	setupEnvironment = name
	if !cmd.Flags().Changed("branch") {
		setupBranch = environment.Branch
	}
	if !cmd.Flags().Changed("domain") {
		setupDomain = environment.Domain
	}
	if !cmd.Flags().Changed("directory") {
		setupDirectory = config.Repository.Directory
	}
	if environment.Prepared == nil {
		return
	}
	if !cmd.Flags().Changed("plan") {
		setupPlan = environment.Prepared.PlanKey
	}
	if !cmd.Flags().Changed("server") {
		setupServerID = environment.Prepared.ServerID
	}
	if !cmd.Flags().Changed("no-charge") {
		setupNoCharge = environment.NoCharge
	}
}

func parseGitHubRemote(remote string) (string, string, error) {
	trimmed := strings.TrimSpace(remote)
	var path string
	if strings.HasPrefix(trimmed, "git@github.com:") {
		path = strings.TrimPrefix(trimmed, "git@github.com:")
	} else {
		parsed, err := url.Parse(trimmed)
		if err != nil || !strings.EqualFold(parsed.Hostname(), "github.com") {
			return "", "", errors.New("the origin remote must point to GitHub")
		}
		path = strings.TrimPrefix(parsed.Path, "/")
	}
	parts := strings.Split(strings.TrimSuffix(path, ".git"), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", errors.New("unable to determine GitHub owner and repository from origin")
	}
	return parts[0], parts[1], nil
}

func validateSetupDomain(value, suggested string) error {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if len(normalized) > 253 || !domainPattern.MatchString(normalized) {
		return errors.New("enter a valid full domain such as example.com")
	}
	if strings.HasSuffix(normalized, ".mycube.dev") && !strings.EqualFold(normalized, suggested) {
		return errors.New("custom mycube.dev names are managed by Intercube; press Enter for the suggestion or use your own domain")
	}
	return nil
}

func validateEnvironment(value string) error {
	value = strings.TrimSpace(value)
	if value == "" {
		return errors.New("environment is required")
	}
	if strings.ContainsAny(value, " /\\") {
		return errors.New("use a short environment name without spaces or slashes")
	}
	return nil
}

func promptValue(label, defaultValue string, validate func(string) error) (string, error) {
	prompt := promptui.Prompt{Label: label, Default: defaultValue, Validate: validate}
	value, err := prompt.Run()
	return strings.TrimSpace(value), err
}

func promptConfirm(label string, defaultValue bool) (bool, error) {
	defaultAnswer := "n"
	if defaultValue {
		defaultAnswer = "y"
	}
	prompt := promptui.Prompt{Label: label, IsConfirm: true, Default: defaultAnswer}
	_, err := prompt.Run()
	if err == promptui.ErrAbort {
		return false, nil
	}
	return err == nil, err
}

func mustConfirm(label string, defaultValue bool) bool {
	value, _ := promptConfirm(label, defaultValue)
	return value
}

func defaultEnvironment(branch string) string {
	if branch == "main" || branch == "master" {
		return "production"
	}
	return "development"
}

func branchEnvironment(branch string) string {
	value := strings.ToLower(strings.TrimSpace(branch))
	value = regexp.MustCompile(`[^a-z0-9-]+`).ReplaceAllString(value, "-")
	value = strings.Trim(value, "-")
	if value == "" {
		return "environment"
	}
	return value
}

func setupIdempotencyKey(owner, repository, environment, branch string) string {
	hash := sha256.Sum256([]byte(strings.ToLower(strings.Join([]string{owner, repository, environment, branch}, ":"))))
	return "cli-setup-" + hex.EncodeToString(hash[:8])
}

func gitOutput(ctx context.Context, args ...string) (string, error) {
	workingDirectory, _ := os.Getwd()
	return gitOutputAt(ctx, workingDirectory, args...)
}

func gitOutputAt(ctx context.Context, directory string, args ...string) (string, error) {
	command := exec.CommandContext(ctx, "git", args...)
	command.Dir = directory
	output, err := command.Output()
	return strings.TrimSpace(string(output)), err
}
